title: ChaiCode Web Development Cohort 2026
description: This repository is the central "Source of Truth" for my journey through the ChaiCode Web Development Cohort, 2026.
remote_theme: pages-themes/hacker
url: "https://web-dev-cohort-2026.sameerbhagtani.dev"
baseurl: ""
markdown: kramdown
