title: ChaiCode Web Development Cohort 2026
description: This repository is the central "Source of Truth" for my journey through the ChaiCode Web Development Cohort, 2026.
theme: jekyll-theme-hacker
markdown: kramdown
